INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, 'Alimentos');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, 'Eletrodomésticos');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, 'Móveis');

INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Arroz', 1);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Feijão', 1);

INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Aspirador de pó', 2);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Batedeira', 2);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Liquidificador', 2);

INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Sofá', 3);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Mesa', 3);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'Estante', 3);
