DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PRODUCT;
DROP SEQUENCE IF EXISTS SEQ_CATEGORY;
DROP SEQUENCE IF EXISTS SEQ_PRODUCT;

CREATE TABLE CATEGORY ( 
   ID INT PRIMARY KEY, 
   CATEGORY NVARCHAR(50) NOT NULL
);
CREATE SEQUENCE SEQ_CATEGORY;

CREATE TABLE PRODUCT ( 
   ID INT PRIMARY KEY,
   NAME NVARCHAR(50) NOT NULL,
   CATEGORY_ID INT NOT NULL,
   FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
CREATE SEQUENCE SEQ_PRODUCT;